### ISSUE TITLE
Look into TTLInOut.count() on counting rising edges

### ISSUE THREAD

**Issue by vontell** [vontell/artiq-control#5]
For rising edge counting, the TTLInOut object has a count() method for retrieving the count of rising edges. If this method is called in the Python code, does this get placed into the event timeline? If I would like to place an event into the timeline after, say, 10 rising edges, can I do this with the count() method? The method in question which would use this functionality is located [here](https://github.com/vontell/artiq-control/blob/master/samples/repository/rle/pipistrello.py#L125)

**Comment by vontell** [comment]
@jordens Do you have any insight on this?

**Comment by jordens** [comment]
https://github.com/m-labs/artiq/blob/master/artiq/coredevice/ttl.py#L264
calling
https://github.com/m-labs/artiq/blob/master/artiq/runtime.rs/libksupport/rtio.rs#L103

You would retrieve timestamps one by one with `timestamp_mu` and then do something after the tenth.

**Comment by jordens** [comment]
If this is a common task that would benefit from extracting logic into gateware, it could amend the counter feature: m-labs/artiq#564

**Comment by vontell** [comment]
Regarding the counter feature, that would be a good idea; I will have to take some time to look into it.

In relation to receiving timestamps using `timestamp_mu`, I was able to get that functionality working by using a while loop which continuously queries for a timestamp of a rising edge. Once I reach a certain threshold, I would like to take the last timestamp, delay by some minimum latency (ideally the minimum latency of the board), and then create a new pulse sequence at that point in the timeline. However, when I attempt placing events into the timeline at this minimum delay, I get negative slack of sometime up to `-196141710 mu`. Is this due to the fact that a while loop is simply not fast enough, and by the time the control CPU realizes that it has reached the threshold, the wall clock is too far beyond the timestamp of the last rising edge? In that case I believe the gateware would be a very helpful feature.

**Comment by vontell** [comment]
Update: the delay needed is about 0.19614171000000002 seconds.

**Comment by jordens** [comment]
That doesn't sound right. Should be a few µs. You obviously can't do anything that's slow. I.e. `print()` and other RPCs in that loop.

**Comment by vontell** [comment]
Without print statements or other heavy operations, I am able to cut the delay down to ~ 0.05 seconds. **Is the following currently possible?** -> At time t=0, starting listening for rising edges on an input. At a time t=D which is a considerable amount of time after t=0, place a pulse sequence. Start the execution of this timeline once both events are placed into the timeline. Once a rising edge is detected at some time t=r, use gateware to change the `rtio_counter` to be at t=D. By doing this, a pulse can be executed without relying on a python while loop, bringing the latency of executing a pulse dependent on an input down to the latency of the board (which I have measured to be much less than a microsecond for the Pipistrello LX45).

**Comment by jordens** [comment]
50 ms is still orders of magnitude to slow. Please reduce it to a test case and let us have a look.

What you want (triggering a pre-calculated sequence of events) at a given offset time is done with [DMA](https://github.com/m-labs/artiq/wiki/DMA). Implementing it the way you suggest would not scale and also break a couple of assumptions for error reporting.

What does "the latency of the board" mean?

**Comment by vontell** [comment]
Sorry, by latency of the board I mean the minimum time allowed to place new events into the timeline after the current time on the board without getting `RTIOUnderflow` and `RTIOCollision` errors. Using DMA will be helpful, but ultimately what I am trying to achieve is placing a new pulse into the timeline just _nanoseconds_, or at least < 100 nanoseconds, after the timestamp of a rising edge.

**Comment by jordens** [comment]
Pretty sure that you can tweak it so that the latency is around 100 ns.
If you need significantly less than 100 ns, then yes, somebody will have to develop the specification and write gateware/runtime support.

**Comment by vontell** [comment]
Ok this makes more sense; thank you @jordens
